services:
  app:
    build: ./
    image: django
    container_name: django-container
    command: gunicorn --bind unix:/app/gunicorn.sock docker.wsgi:application
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=docker.settings_postgres
    env_file:
      - .env
    working_dir: /app
    volumes:
      - static_volume:/app/static
    networks:
      - docker-network
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    container_name: postgres-container
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=djangodata
    networks:
      - docker-network

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - docker-network
    depends_on:
      - app
  
volumes:
  postgres-volume:
    name: postgres-data
