services:
  app:
    build: ./
    image: django
    container_name: django-container
    command: gunicorn --bind 0.0.0.0:8000 docker.wsgi:application
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=docker.settings_postgres
    volumes:
      - static-volume:/app/static
    networks:
      - docker-network
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    container_name: postgres-container
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.postgres
    networks:
      - docker-network

  nginx:
    image: nginx
    container_name: nginx-container
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - docker-network
    depends_on:
      - app
  
volumes:
  postgres-volume:
    name: postgres-data
  static-volume:
    name: static

networks:
  docker-network:
    name: docker-network
   